version: '3.10'

services:
  web:
    build: .
    command: python3 manage.py runserver 0.0.0.0:8000
    # マウント場所の指定
    volumes:
      - .:/hometasker
    ports:
      - "8000:8000"
    # dbサービスが立ち上がってから起動するように指定
    depends_on:
      - db

  db:
    image: mysql:8.0.28
    ports: 
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: hometasker
      TZ: "Asia/Tokyo"